openapi: 3.0.3
info:
  title: Calendar API
  version: 1.0.0
  description: API do zarządzania kalendarzami i wydarzeniami

paths:
  /api/calendars:
    $ref: './paths/calendar/calendars.yaml'

  /api/calendars/{calendarId}:
    $ref: './paths/calendar/calendars-by-id.yaml'

  /api/events:
    $ref: './paths/event/events.yaml'

  /api/events/search:
    $ref: './paths/event/events-search.yaml'

  /api/events/{eventId}:
    $ref: './paths/event/events-by-id.yaml'

  /api/attendees/{eventId}:
    $ref: './paths/attendee/add-attendees-to-event.yaml'

  /api/attendees/{eventId}/respond:
    $ref: './paths/attendee/respond-to-event.yaml'

  /api/attendees/event/{eventId}/attendee/{attendeeId}:
    $ref: './paths/attendee/delete-attendee.yaml'

components:
  schemas:
    AttendeeDto:
      $ref: './components/schemas/AttendeeDto.yaml'
    CalendarDto:
      $ref: './components/schemas/CalendarDto.yaml'
    EventDto:
      $ref: './components/schemas/EventDto.yaml'
    FilterRequest:
      $ref: './components/schemas/FilterRequest.yaml'
    PageRequest:
      $ref: './components/schemas/PageRequest.yaml'
    SearchFilter:
      $ref: './components/schemas/SearchFilter.yaml'
    SortRequest:
      $ref: './components/schemas/SortRequest.yaml'
    ResponseStatusDto:
      $ref: './components/schemas/enums/ResponseStatusDto.yaml'
    EventStatus:
      $ref: './components/schemas/enums/EventStatus.yaml'